apiVersion: v1
kind: Service
metadata:
  name:  rstudio-node-port-dev
spec:
  type: NodePort
  ports:
    - port: 3100
      targetPort: 8787
      nodePort: 31550
      name: http
    - port: 3200
      targetPort: 22
      nodePort: 31600
      name: ssh
  selector:
    component: rstudio-dev
